name: deps
on:
  schedule:
    - cron: "29 7 * * *"
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'
      - name: check for outdated dependencies
        id: deps
        run: if [[ ! $(clojure -M:outdated --fail) ]]; then echo ::set-output name=status::failure; else echo ::set-output name=status::success; fi
      - if: ${{ steps.deps.outputs.status == 'failure' }}
        name: Update stale dependencies
        run: clojure -M:outdated --write
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updating stale dependencies
          title: Update stale dependencies
          body: Updating dependencies to the latest stable versions
          branch: update-dependencies
          base: main
